Repository CodingSlaved/Diary, pull requests merged in 2025-04, with the labels that each got.

#2 글쓰기 페이지 개발
  .idea/codeStyles/Project.xml
  .idea/codeStyles/codeStyleConfig.xml
  .idea/compiler.xml
  .idea/deploymentTargetSelector.xml
  .idea/gradle.xml
  .idea/misc.xml
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/codingslaved/diary/DiaryApplication.kt
  app/src/main/java/com/codingslaved/diary/MainActivity.kt
  app/src/main/java/com/codingslaved/diary/data/container/DiaryContainer.kt
  app/src/main/java/com/codingslaved/diary/data/dao/DiaryDao.kt
  app/src/main/java/com/codingslaved/diary/data/database/DiaryDatabase.kt
  app/src/main/java/com/codingslaved/diary/data/model/Diary.kt
  app/src/main/java/com/codingslaved/diary/data/repository/DiaryRepository.kt
  app/src/main/java/com/codingslaved/diary/data/repository/DiaryRepositoryImpl.kt
  app/src/main/java/com/codingslaved/diary/view/WritingScreen.kt
  app/src/main/java/com/codingslaved/diary/viewmodel/DiaryEntryViewModel.kt
  app/src/main/java/com/codingslaved/diary/viewmodel/DiaryProvider.kt
  build.gradle.kts
Labels: enhancement

#6 fix/save-problem
  app/src/main/java/com/codingslaved/diary/view/WritingScreen.kt
Labels: bug

#7 Fix/calendar
  app/src/main/java/com/codingslaved/diary/ui/Navigation.kt
  app/src/main/java/com/codingslaved/diary/ui/screens/calendar/month/MonthDataSource.kt
  app/src/main/java/com/codingslaved/diary/ui/screens/calendar/week/WeekDataSource.kt
  app/src/main/java/com/codingslaved/diary/view/HomeScreen.kt
  app/src/main/java/com/codingslaved/diary/view/WritingScreen.kt
  app/src/main/java/com/codingslaved/diary/view/calendar/CalendarScreen.kt
  app/src/main/java/com/codingslaved/diary/view/calendar/month/MonthCalendar.kt
  app/src/main/java/com/codingslaved/diary/view/calendar/month/MonthDataSource.kt
  app/src/main/java/com/codingslaved/diary/view/calendar/month/MonthViewModel.kt
  app/src/main/java/com/codingslaved/diary/view/calendar/week/WeekCalendar.kt
  app/src/main/java/com/codingslaved/diary/view/calendar/week/WeekDataSource.kt
  app/src/main/java/com/codingslaved/diary/view/calendar/week/WeekViewModel.kt
Labels: bug, enhancement

#8 HQT-6 Diary 엔티티의 date Column 타입 컨버터 개발
  app/src/main/java/com/codingslaved/diary/data/converter/Converters.kt
  app/src/main/java/com/codingslaved/diary/data/dao/DiaryDao.kt
  app/src/main/java/com/codingslaved/diary/data/database/DiaryDatabase.kt
  app/src/main/java/com/codingslaved/diary/data/model/Diary.kt
  app/src/main/java/com/codingslaved/diary/data/repository/DiaryRepository.kt
  app/src/main/java/com/codingslaved/diary/data/repository/DiaryRepositoryImpl.kt
  app/src/main/java/com/codingslaved/diary/view/WritingScreen.kt
  app/src/main/java/com/codingslaved/diary/view/calendar/CalendarScreen.kt
  app/src/main/java/com/codingslaved/diary/viewmodel/DiaryEntryViewModel.kt
Labels: enhancement
